// Generated by CoffeeScript 1.3.3
(function() {
  "use strict";

  var chrome, cmd, fb, firebug, global,
    __slice = [].slice;

  global = window;

  fb = global.Firebug;

  chrome = fb.chrome;

  cmd = fb.CommandLine;

  firebug = {
    info: {
      version: '0.1.3',
      open: "open firebug window",
      close: "minimize firebug window",
      toggle: "toggle firebug window",
      disable: "exit from firebug",
      console: "open console and set focus",
      multiline: "multiline console",
      "toggle-console": "toggle between one-line and multiline console",
      clear: "clear console output window",
      run: "run script that was entered in console editor",
      'tab': "focuses the specified firebug tab (console, html, stylesheet, script, dom, net, etc)",
      'tab-side': "focuses the specified firebug side tab (css, computed, layout, dom, domSide, watch)",
      '>': "focuses the next firebug tab(right)",
      '<': "focuses the next firebug tab(left)",
      '#': "focuses the prev firebug tab",
      '/': "search",
      inspect: "toggle the firebug element inspector"
    },
    open: function() {
      if (!chrome.isOpen()) {
        return fb.toggleBar(true, 'console');
      }
    },
    close: function() {
      if (chrome.isOpen()) {
        return fb.toggleBar();
      }
    },
    toggle: function() {
      return fb.toggleBar();
    },
    disable: function() {
      return fb.closeFirebug(true);
    },
    inspect: function() {
      if (!fb.currentContext) {
        fb.toggleBar(true);
      }
      return fb.Inspector.toggleInspecting(fb.currentContext);
    },
    console: function() {
      var cmEditor, cmLine;
      if (!chrome.isOpen()) {
        this.open();
      }
      chrome.switchToPanel(fb.currentContext, "console");
      cmLine = cmd.getSingleRowCommandLine();
      cmEditor = cmd.getCommandEditor();
      if (fb.commandEditor) {
        if (cmEditor.focus) {
          return cmEditor.focus();
        } else {
          return cmEditor.select();
        }
      } else {
        return cmLine.select();
      }
    },
    multiline: function() {
      if (chrome.isOpen()) {
        return cmd.toggleMultiLine(true);
      }
    },
    "toggle-console": function() {
      if (chrome.isOpen()) {
        return cmd.toggleMultiLine();
      }
    },
    clear: function() {
      if (chrome.isOpen()) {
        return fb.Console.clear();
      }
    },
    run: function() {
      if (chrome.isOpen()) {
        return cmd.enter(fb.currentContext);
      }
    },
    'tab': function(panelName) {
      if (panelName == null) {
        panelName = "console";
      }
      if (chrome.isOpen()) {
        return chrome.navigate(null, panelName);
      }
    },
    'tab-side': function(panelName) {
      if (chrome.isOpen()) {
        return chrome.selectSidePanel(panelName);
      }
    },
    '>': function() {
      if (chrome.isOpen()) {
        return chrome.gotoSiblingTab(true);
      }
    },
    '<': function() {
      if (chrome.isOpen()) {
        return chrome.gotoSiblingTab();
      }
    },
    '#': function() {
      if (chrome.isOpen()) {
        return chrome.gotoPreviousTab();
      }
    },
    '/': function() {
      var text;
      text = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (chrome.isOpen()) {
        fb.Search.focus(fb.currentContext);
        return fb.Search.search(text.join(' '), fb.currentContext);
      }
    },
    _initialize: function() {
      fb = global.Firebug;
      chrome = fb.chrome;
      return cmd = fb.CommandLine;
    }
  };

  group.commands.add(['firebug', 'fbpc'], "firebug-pentadactyl (version " + firebug.info.version + ")", function(args) {
    var command, index, _i, _len, _results;
    if (!chrome) {
      firebug._initialize();
    }
    _results = [];
    for (index = _i = 0, _len = args.length; _i < _len; index = ++_i) {
      command = args[index];
      if (firebug[command]) {
        _results.push(firebug[command].apply(firebug, args.slice(index + 1)));
      }
    }
    return _results;
  }, {
    completer: function(context) {
      var name;
      return context.completions = (function() {
        var _results;
        _results = [];
        for (name in firebug) {
          if (name !== 'info' || name.indexOf('_')) {
            _results.push([name, firebug.info[name]]);
          }
        }
        return _results;
      })();
    }
  });

  group.options.add(["fbliverun"], "run script on blur firebug console", "boolean", false, {
    setter: function(value) {
      var cmEditor;
      if (!cmd) {
        firebug._initialize();
      }
      cmEditor = cmd.getCommandEditor();
      if (value) {
        return cmEditor.editor.addEventListener('blur', firebug.run);
      } else if (!value) {
        return cmEditor.editor.removeEventListener('blur', firebug.run);
      }
    }
  });

}).call(this);
